package com.bpkpad.peminjaman.peminjaman.domain.model.enums

enum class AuditAction(val code: String) {
    LOGIN("LOGIN"),
    LOGOUT("LOGOUT"),
    TRANSAKSI_DIBUAT("TRANSAKSI_DIBUAT"),
    TRANSAKSI_DIEDIT("TRANSAKSI_DIEDIT"),
    PENGAJUAN_DIKIRIM("PENGAJUAN_DIKIRIM"),
    DISETUJUI_ONLINE("DISETUJUI_ONLINE"),
    DISETUJUI_BYPASS("DISETUJUI_BYPASS"),
    BYPASS_DIAKUI_KASUBAG("BYPASS_DIAKUI_KASUBAG"),
    DITOLAK("DITOLAK"),
    DOKUMEN_DISERAHKAN("DOKUMEN_DISERAHKAN"),
    PERPANJANGAN_DIAJUKAN("PERPANJANGAN_DIAJUKAN"),
    PERPANJANGAN_DISETUJUI("PERPANJANGAN_DISETUJUI"),
    PERPANJANGAN_DITOLAK("PERPANJANGAN_DITOLAK"),
    DIKEMBALIKAN_BAIK("DIKEMBALIKAN_BAIK"),
    DIKEMBALIKAN_RUSAK("DIKEMBALIKAN_RUSAK"),
    DIKEMBALIKAN_HILANG("DIKEMBALIKAN_HILANG"),
    DIBATALKAN("DIBATALKAN"),
    MASTER_DOKUMEN_DITAMBAH("MASTER_DOKUMEN_DITAMBAH"),
    MASTER_DOKUMEN_DIEDIT("MASTER_DOKUMEN_DIEDIT"),
    MASTER_INSTANSI_DITAMBAH("MASTER_INSTANSI_DITAMBAH"),
    MASTER_INSTANSI_DIEDIT("MASTER_INSTANSI_DIEDIT");

    companion object {
        fun fromCode(code: String): AuditAction = entries.firstOrNull { it.code == code } ?: TRANSAKSI_DIBUAT
    }
}
